import Head from 'next/head';
import Layout from '../components/Layout';

export default function About() {
  return (
    <Layout>
      <Head>
        <title>About</title>
        <meta name="about" content="Generated by create next app" />
      </Head>
      <h1>Welcome to the About Page</h1>
    </Layout>
  );
}
